# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.distanceMatrixSmoothing <- function(dmat, umat, add) {
    .Call(`_ecosmooth_distanceMatrixSmoothing`, dmat, umat, add)
}

.rectangularMatrixSmoothing <- function(smat, umat) {
    .Call(`_ecosmooth_rectangularMatrixSmoothing`, smat, umat)
}

